import { useState } from "react";
import Head from "next/head";
import styled from "styled-components";
import RatingScreen from "../components/RatingScreen";
import ThankYouScreen from "../components/ThankYouScreen";

const Wrapper = styled.div`
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: hsl(216, 12%, 8%);
`;

export default function Home() {
  const [submitted, setSubmitted] = useState(false);
  const [value, setValue] = useState(null);

  return (
    <Wrapper>
      <Head>
        <title>Rating Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      {!submitted ? (
        <RatingScreen setValue={setValue} setSubmitted={setSubmitted} />
      ) : (
        <ThankYouScreen value={value} />
      )}
    </Wrapper>
  );
}
